# Generated by Django 4.2 on 2024-07-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helicopter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helicopter',
            name='rent_price',
            field=models.IntegerField(verbose_name='Стоимость аренды, 1 час'),
        ),
    ]
