# Generated by Django 4.2 on 2024-07-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helicopter', '0002_alter_helicopter_rent_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('number_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('model_starship', models.CharField(verbose_name='Модель звездолета')),
                ('number_of_passengers', models.IntegerField(verbose_name='Количество пассажиров')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('helicopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='helicopter.helicopter', verbose_name='Вертолет')),
            ],
        ),
    ]
